api:
  paths:
    configs_dir: "../configs"
    tmp_dir: "../tmp"
    uploads_dir: "{tmp_dir}/uploads"
    data_dir: "../data"
    security_dir: "{data_dir}/security"
    ssl_dir: "{data_dir}/security/ssl"
    asymmetric_keys_dir: "{data_dir}/security/asymmetric_keys"
