services:
  api:
    volumes:
      - "./volumes/storage/webui-auto-miner/logs:${WUM_API_LOGS_DIR:-/var/log/webui-auto-miner}"
      - "./volumes/storage/webui-auto-miner/data:${WUM_API_DATA_DIR:-/var/lib/webui-auto-miner}"
      - "./scripts/docker/docker-entrypoint.sh:/usr/local/bin/docker-entrypoint.sh"
      - "./src:/app/webui-auto-miner"
      - "./volumes/.vscode-server:/home/wuc-user/.vscode-server"
    # deploy:
    #   replicas: 0
    #   resources:
    #     limits:
    #       cpus: "0.5"
    #       memory: 512M
    # command: ["/bin/bash"]
    # command: ["-b", "uvicorn main:app --host=0.0.0.0 --port=${WUM_API_PORT:-10001} --no-access-log --no-server-header --proxy-headers --forwarded-allow-ips='*' --reload --reload-include='*.yml' --reload-include='.env'"]
    # healthcheck:
    #   test: ["CMD-SHELL", "curl -f http://localhost:${WUM_API_PORT:-10001}/ping"]
    #   start_period: 30s
    #   start_interval: 1s
    #   interval: 5m
    #   timeout: 5s
    #   retries: 3
