services:
  miner-api:
    image: rest.rt-wu-miner:latest
    build:
      context: .
      platforms:
        - linux/amd64
    restart: unless-stopped
    environment:
      TERM: ${TERM:-xterm}
      TZ: ${TZ:-UTC}
      WUM_API_PORT: ${WUM_API_PORT:-8000}
      # DOCKER_HOST_INTERNAL: host.docker.internal # comment out for production
    env_file:
      - path: .env
        required: false
    ports:
      - "${WUM_API_PORT:-10002}:${WUM_API_PORT:-10002}"
    tty: true