nav:
  - README.md
  - Active Challenges:
      - ab_sniffer: ./ab_sniffer
      - bot_virus: ./bot_virus
  - Inactive Challenges:
      - flowradar: ./flowradar
      - flowprint: ./flowprint
      - historical_fingerprinter: ./historical_fingerprinter
      - dev_fingerprinter: ./dev_fingerprinter
      - ada_detection: ./ada_detection
      - humanize_behaviour: ./humanize_behaviour
