nav:
  - README.md
  - Active Challenges:
      - ada_detection: ./ada_detection
      - dev_fingerprinter: ./dev_fingerprinter
  - Inactive Challenges:
      - humanize_behaviour: ./humanize_behaviour
      - ab_sniffer: ./ab_sniffer
