nav:
  - README.md
  - Active Challenges:
      - ab_sniffer: ./ab_sniffer
      - flowradar vpn detection: ./flowradar
      - flowprint os classification: ./flowprint
  - Inactive Challenges:
      - historical_fingerprinter: ./historical_fingerprinter
      - dev_fingerprinter: ./dev_fingerprinter
      - ada_detection: ./ada_detection
      - humanize_behaviour: ./humanize_behaviour
