services:
  webui_auto:
    image: rest.rt-wu-challenger:latest
    build:
      context: .
    restart: unless-stopped
    environment:
      TERM: ${TERM:-xterm}
      TZ: ${TZ:-UTC}
      WUC_API_PORT: ${WUC_API_PORT:-10001}
    env_file:
      - path: .env
        required: false
    volumes:
      - "api-logs:${WUC_API_LOGS_DIR:-/var/log/rest.rt-wu-challenger}"
      - "api-data:${WUC_API_DATA_DIR:-/var/lib/rest.rt-wu-challenger}"
    ports:
      - "${WUC_API_PORT:-10001}:${WUC_API_PORT:-10001}"
    tty: true


volumes:
  api-logs:
  api-data:
