env: "LOCAL"
debug: false

api:
  name: "Web UI Automation Challenger"
  slug: "rest.rt-wu-challenger"
  bind_host: "0.0.0.0"
  port: 10001
  version: "1"
  prefix: ""
  gzip_min_size: 1024 # Bytes (1KB)
  behind_proxy: true
  behind_cf_proxy: true
  dev:
    reload: false
    reload_includes: [".env", "*.json", "*.yml", "*.yaml", "*.md"]
    reload_excludes:
      [".*", "~*", ".py[cod]", ".sw.*", "__pycache__", "*.log", "logs"]

web:
  url: "https://webui_auto:10001/web"
