api:
  docs:
    enabled: true
    openapi_url: "{api_prefix}/openapi.json"
    docs_url: "{api_prefix}/docs"
    redoc_url: "{api_prefix}/redoc"
    swagger_ui_oauth2_redirect_url: "{api_prefix}/docs/oauth2-redirect"
    summary: "This is the API documentation for the Web UI Automation Challenger."
    openapi_tags:
      - name: "Utils"
        description: "Useful utility endpoints."
    swagger_ui_parameters:
      syntaxHighlight.theme: "nord"
