api:
  security:
    allowed_hosts: ["*"]
    forwarded_allow_ips: ["*"]
    cors:
      allow_origins: ["*"]
      allow_origin_regex: null
      allow_headers: ["*"]
      allow_methods:
        ["GET", "POST", "PUT", "PATCH", "DELETE", "HEAD", "OPTIONS", "CONNECT"]
      allow_credentials: false
      expose_headers: []
      max_age: 600 # Seconds (10 minutes)
    ssl:
      enabled: true
      cert_fname: "cert.pem"
      key_fname: "key.pem"
    asymmetric:
      generate: true
      algorithm: "RS256"
      key_size: 2048
      private_key_fname: "private_key.pem"
      public_key_fname: "public_key.pem"
