nav:
  - Home: README.md
  - Getting Started: getting_started
  - Miner: miner/
  - Validator: validator/
  - Challenges: challenges/
  - Manuals: manuals/
  # - "*"
  # - Development: dev/
  - Release Notes: release-notes.md
  - About: about/
