nav:
  - Home: README.md
  - Miner: miner/
  - Validator: validator/
  - Challenges: challenges/
  - Guides: guides/
  # - "*"
  - Development: dev/
  - Release Notes: release-notes.md
  - About: about/
