nav:
  - Home: README.md
  - Getting Started: getting-started/
  - Miner: miner/
  - Validator: validator/
  - Challenges: challenges/
  - Manuals: manuals/
  - release-notes.md
  - About: about/

exclude_docs: |
  dev/
  diagrams/
