name: 1. Bump Version

on:
  workflow_dispatch:
    inputs:
      bump_type:
        type: choice
        description: "Choose bump version type:"
        required: true
        options: ["patch", "minor", "major"]
      miner_bump_type:
        type: choice
        description: "Miner bump version type:"
        required: true
        default: "patch"
        options: ["patch", "minor", "major"]
      validator_bump_type:
        type: choice
        description: "Validator bump version type:"
        required: true
        default: "patch"
        options: ["patch", "minor", "major"]
      reward_validator_bump_type:
        type: choice
        description: "Reward validator bump version type:"
        required: true
        default: "patch"
        options: ["patch", "minor", "major"]

jobs:
  # test:
  #   name: 1.1. Test
  #   runs-on: ubuntu-22.04
  #   permissions:
  #     contents: read
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v4
  #     - name: Set up Python
  #       uses: actions/setup-python@v5
  #       with:
  #         python-version: "3.10"
  #     - name: Install dependencies
  #       run: |
  #         python -m pip install -U pip
  #         python -m pip install -r ./requirements/requirements.test.txt
  #     - name: Test with pytest
  #       run: ./scripts/test.sh -l

  bump_version:
    # needs: test
    name: 1.2. Bump Version
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Save bump types to artifacts
        run: |
          mkdir -p bump-config
          echo "${{ inputs.miner_bump_type }}" > bump-config/miner_bump_type.txt
          echo "${{ inputs.validator_bump_type }}" > bump-config/validator_bump_type.txt
          echo "${{ inputs.reward_validator_bump_type }}" > bump-config/reward_validator_bump_type.txt

      - name: Upload bump types
        uses: actions/upload-artifact@v4
        with:
          name: bump-types
          path: bump-config/
          retention-days: 1

      - name: Bump version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          ./scripts/bump-version.sh -b=${{ inputs.bump_type }} -c -t -p
