api:
  paths:
    tmp_dir: "../data/tmp"
    uploads_dir: "{tmp_dir}/uploads"
    data_dir: "../data"
    security_dir: "{data_dir}/security"
    asymmetric_keys_dir: "{data_dir}/security/asymmetric_keys"
